name: brick_breaker
description: "Re-implementing Woz's Breakout"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.1
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

# Configuración del icono de la app
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"

# Configuración del splash screen
flutter_native_splash:
  color: "#f2e8cf"
  image: assets/images/icon.png
  android: true
  ios: true
  web: true
  
  android_12:
    image: assets/images/icon.png
    color: "#f2e8cf"
  
  web_image_mode: center